import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:sales_power/components/appbbar_default.dart';
import 'package:sales_power/models/product.dart';


class ProductDetailPage extends StatelessWidget {
  final Product product;

  const ProductDetailPage({this.product});
  AddProdutos();

  @override
  Widget build(BuildContext context) {
    return Container(

      child: Scaffold(
        backgroundColor: Colors.transparent,
        appBar: AppBarDefault(
          titulo: '',
        ),
        body: Align(
          alignment: Alignment.bottomCenter,
          child: Container(
            height: 400,
            margin: EdgeInsets.all(16),
            child: Detail(product: product),
          ),
        ),
      ),
    );
  }

  noSuchMethod(Invocation invocation) => super.noSuchMethod(invocation);
}
Future<void> AddProdutos() async {

final List productsList = [
{"description": "SAB PHEBO 12X90", "stock" : 1, "price" : 23.23},
{"description": "SAB PHEBO 12X90", "stock" : 862, "price" : 23.97},
{"description": "AP BARB BIC COM", "stock" : 2183, "price" : 22.49},
{"description": "SAB SENADOR 12X", "stock" : 249, "price" : 29.01},
{"description": "DESOD SPRAY ALM", "stock" : 86, "price" : 36.26},
{"description": "SAB ALMA FLORES", "stock" : 53, "price" : 29.10},
{"description": "DESOD SPRAY SEN", "stock" : 67, "price" : 38.25},
{"description": "ESMALTE IMPALA ", "stock" : 244, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 263, "price" : 11.05},
{"description": "ESMALTE IMPALA ", "stock" : 323, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 238, "price" : 11.05},
{"description": "ESMALTE IMPALA ", "stock" : 210, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 238, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 224, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 191, "price" : 10.31},
{"description": "ESMALTE IMPALA ", "stock" : 279, "price" : 11.05},
{"description": "TALCO BARLA GDE", "stock" : 472, "price" : 40.01},
{"description": "ESMALTE IMPALA ", "stock" : 169, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 396, "price" : 11.05},
{"description": "ESMALTE IMPALA ", "stock" : 761, "price" : 10.24},
{"description": "ESMALTE IMPALA ", "stock" : 206, "price" : 10.30},
{"description": "ESMALTE IMPALA ", "stock" : 48, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 526, "price" : 10.25},
{"description": "ESMALTE IMPALA ", "stock" : 133, "price" : 11.05},
{"description": "ESMALTE IMPALA ", "stock" : 151, "price" : 10.31},
{"description": "ESMALTE IMPALA ", "stock" : 196, "price" : 11.05},
{"description": "ESMALTE IMPALA ", "stock" : 321, "price" : 11.05},
{"description": "ANT-SEPT BUC CO", "stock" : 1000, "price" : 25.35},
{"description": "CR DT SORRISO D", "stock" : 3, "price" : 42.03},
{"description": "CR DT SORRISO D", "stock" : 529, "price" : 16.27},
{"description": "CR DT SORRISO F", "stock" : 14, "price" : 29.27},
{"description": "CR DT COLG PREV", "stock" : 37, "price" : 85.49},
{"description": "CR DT TANDY MOR", "stock" : 99, "price" : 46.67},
{"description": "CR DT SORRISO D", "stock" : 1360, "price" : 24.98},
{"description": "CR DT COLG TRIP", "stock" : 1615, "price" : 26.99},
{"description": "CR DT COLG MPA ", "stock" : 808, "price" : 16.19},
{"description": "CR DT TANDY TUT", "stock" : 130, "price" : 46.65},
{"description": "FIO DENTAL COLG", "stock" : 286, "price" : 33.75},
{"description": "ESC DT SORRISO ", "stock" : 203, "price" : 20.57},
{"description": "ESC DT SORRISO ", "stock" : 181, "price" : 20.57},
{"description": "ESC DT SORRISO ", "stock" : 172, "price" : 20.57},
{"description": "ESMALTE IMPALA ", "stock" : 349, "price" : 10.26},
{"description": "AP BARB BIC COM", "stock" : 1812, "price" : 22.49},
{"description": "ESMALTE IMPALA ", "stock" : 999, "price" : 10.24},
{"description": "AP BARB BIC SEN", "stock" : 666, "price" : 12.77},
{"description": "SAB SENADOR 12X", "stock" : 73, "price" : 28.42},
{"description": "ESMALTE IMPALA ", "stock" : 1851, "price" : 10.22},
{"description": "ESMALTE IMPALA ", "stock" : 527, "price" : 10.25},
{"description": "ESMALTE IMPALA ", "stock" : 458, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 311, "price" : 10.26},
{"description": "SAB PALM NATURA", "stock" : 327, "price" : 18.84},
{"description": "ESMALTE IMPALA ", "stock" : 1014, "price" : 10.24},
{"description": "CR DT SORRISO S", "stock" : 800, "price" : 24.96},
{"description": "CR DT SORRISO S", "stock" : 490, "price" : 16.26},
{"description": "CR DT SORRISO S", "stock" : 348, "price" : 42.08},
{"description": "ABS INTIMUS GEL", "stock" : 300, "price" : 19.10},
{"description": "ABS INTIMUS GEL", "stock" : 1, "price" : 19.10},
{"description": "HASTES FLEX COT", "stock" : 821, "price" : 9.82},
{"description": "ESMALTE IMPALA ", "stock" : 115, "price" : 11.05},
{"description": "CR DT COLG SENS", "stock" : 18, "price" : 133.08},
{"description": "SAB PALM NATURA", "stock" : 654, "price" : 18.82},
{"description": "SAB PALM NATURA", "stock" : 555, "price" : 18.82},
{"description": "SAB PALM NATURA", "stock" : 600, "price" : 18.86},
{"description": "CR DT COLG TOTA", "stock" : 813, "price" : 59.37},
{"description": "CR DT COLG TOTA", "stock" : 106, "price" : 59.46},
{"description": "CR DT COLG TRIP", "stock" : 674, "price" : 27.03},
{"description": "CR DT COLG MPA ", "stock" : 1190, "price" : 46.34},
{"description": "ESC DT COLG INF", "stock" : 10, "price" : 11.57},
{"description": "CR DT COLG SENS", "stock" : 13, "price" : 132.92},
{"description": "ESMALTE IMPALA ", "stock" : 252, "price" : 10.26},
{"description": "CR DT COLG TOTA", "stock" : 179, "price" : 59.37},
{"description": "DESOD ROLL-ON R", "stock" : 121, "price" : 17.47},
{"description": "ABS INTIMUS GEL", "stock" : 1, "price" : 19.10},
{"description": "ABS INTIMUS GEL", "stock" : 6, "price" : 19.10},
{"description": "SAB DOVE 12X90 ", "stock" : 229, "price" : 23.76},
{"description": "SAB DOVE 12X90 ", "stock" : 76, "price" : 23.84},
{"description": "ALGODAO COTTON ", "stock" : 113, "price" : 13.36},
{"description": "AP BARB BIC COM", "stock" : 423, "price" : 11.97},
{"description": "ESC DT ORAL B I", "stock" : 7, "price" : 67.99},
{"description": "SAB SENADOR 12X", "stock" : 107, "price" : 28.42},
{"description": "AP BARB BIC COM", "stock" : 2016, "price" : 21.77},
{"description": "AP BARB BIC COM", "stock" : 2385, "price" : 21.76},
{"description": "FIO DENTAL COLG", "stock" : 227, "price" : 33.67},
{"description": "ABS INTIMUS GEL", "stock" : 253, "price" : 2.33},
{"description": "ABS INTIMUS GEL", "stock" : 510, "price" : 2.33},
{"description": "ESMALTE IMPALA ", "stock" : 441, "price" : 11.05},
{"description": "SAB LIQ PROTEX ", "stock" : 1, "price" : 19.26},
{"description": "ESMALTE IMPALA ", "stock" : 204, "price" : 10.26},
{"description": "SAB ALMA FLORES", "stock" : 72, "price" : 28.89},
{"description": "HASTES FLEX MIL", "stock" : 113, "price" : 37.31},
{"description": "ESMALTE IMPALA ", "stock" : 161, "price" : 10.31},
{"description": "ESMALTE IMPALA ", "stock" : 166, "price" : 10.30},
{"description": "COND PALM NATUR", "stock" : 35, "price" : 35.89},
{"description": "COND PALM NATUR", "stock" : 976, "price" : 35.89},
{"description": "COND PALM NATUR", "stock" : 33, "price" : 35.89},
{"description": "COND PALM NATUR", "stock" : 84, "price" : 51.74},
{"description": "COND PALM NATUR", "stock" : 11, "price" : 51.74},
{"description": "COND PALM NATUR", "stock" : 47, "price" : 35.89},
{"description": "SH PALM NATURAL", "stock" : 9, "price" : 30.53},
{"description": "SH PALM NATURAL", "stock" : 112, "price" : 50.23},
{"description": "SH PALM NATURAL", "stock" : 105, "price" : 30.53},
{"description": "SH PALM NATURAL", "stock" : 3, "price" : 30.53},
{"description": "SH PALM NATURAL", "stock" : 117, "price" : 30.53},
{"description": "SH PALM NATURAL", "stock" : 81, "price" : 47.22},
{"description": "SH PALM NATURAL", "stock" : 137, "price" : 47.22},
{"description": "SH PALM NATURAL", "stock" : 36, "price" : 30.53},
{"description": "SH PALM NATURAL", "stock" : 47, "price" : 30.53},
{"description": "SAB SENADOR 12X", "stock" : 72, "price" : 28.42},
{"description": "SH PALM NATURAL", "stock" : 76, "price" : 50.23},
{"description": "ESMALTE IMPALA ", "stock" : 112, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 157, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 271, "price" : 10.31},
{"description": "ESMALTE IMPALA ", "stock" : 242, "price" : 11.05},
{"description": "ESMALTE IMPALA ", "stock" : 168, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 156, "price" : 10.25},
{"description": "ESMALTE IMPALA ", "stock" : 108, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 1283, "price" : 11.05},
{"description": "ESMALTE IMPALA ", "stock" : 1413, "price" : 10.24},
{"description": "COND DARLING 6X", "stock" : 998, "price" : 28.70},
{"description": "COND DARLING 6X", "stock" : 480, "price" : 28.70},
{"description": "SH DARLING 6X35", "stock" : 56, "price" : 24.13},
{"description": "SH DARLING 6X35", "stock" : 77, "price" : 24.12},
{"description": "SH DARLING 6X35", "stock" : 74, "price" : 24.16},
{"description": "ESMALTE IMPALA ", "stock" : 203, "price" : 10.30},
{"description": "ESMALTE IMPALA ", "stock" : 123, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 369, "price" : 10.26},
{"description": "SH PALM NATURAL", "stock" : 31, "price" : 30.52},
{"description": "COND PALM NATUR", "stock" : 64, "price" : 35.89},
{"description": "AP BARB BIC COM", "stock" : 107, "price" : 52.22},
{"description": "ESMALTE IMPALA ", "stock" : 127, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 237, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 154, "price" : 11.05},
{"description": "ESMALTE IMPALA ", "stock" : 100, "price" : 11.05},
{"description": "KIT SH + COND N", "stock" : 1, "price" : 7.42},
{"description": "KIT SH + COND N", "stock" : 463, "price" : 7.46},
{"description": "ESC DT INF ORAL", "stock" : 159, "price" : 54.67},
{"description": "CR DT SORRISO D", "stock" : 1260, "price" : 24.86},
{"description": "ALGODAO COTTON ", "stock" : 47, "price" : 23.78},
{"description": "ESMALTE IMPALA ", "stock" : 64, "price" : 11.05},
{"description": "ESMALTE IMPALA ", "stock" : 110, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 150, "price" : 10.26},
{"description": "ANT-SEPT BUC CO", "stock" : 74, "price" : 17.76},
{"description": "KIT SH + COND N", "stock" : 1229, "price" : 7.43},
{"description": "CR DT COLG TOTA", "stock" : 69, "price" : 59.53},
{"description": "ABS INTIMUS DAY", "stock" : 176, "price" : 25.37},
{"description": "SAB DOVE MEN CA", "stock" : 89, "price" : 21.41},
{"description": "HASTES FLEX COT", "stock" : 164, "price" : 9.35},
{"description": "SAB PALM NATURA", "stock" : 641, "price" : 18.87},
{"description": "DESOD ROLL-ON R", "stock" : 30, "price" : 17.38},
{"description": "CARGA P/AP BARB", "stock" : 49, "price" : 21.72},
{"description": "SH PALM NATURAL", "stock" : 18, "price" : 30.58},
{"description": "COND PALM NATUR", "stock" : 36, "price" : 35.89},
{"description": "ESMALTE IMPALA ", "stock" : 270, "price" : 12.26},
{"description": "ESMALTE IMPALA ", "stock" : 270, "price" : 12.26},
{"description": "ESMALTE IMPALA ", "stock" : 1051, "price" : 12.16},
{"description": "SAB DOVE 12X90 ", "stock" : 33, "price" : 23.95},
{"description": "ANT-SEPT BUC CO", "stock" : 145, "price" : 25.35},
{"description": "SAB LIQ PALM NA", "stock" : 99, "price" : 13.39},
{"description": "AP BARB BIC COM", "stock" : 2069, "price" : 21.77},
{"description": "AP BARB BIC COM", "stock" : 101, "price" : 52.22},
{"description": "SAB DOVE 12X90 ", "stock" : 80, "price" : 21.43},
{"description": "SAB PALM NATURA", "stock" : 202, "price" : 18.83},
{"description": "SAB REXONA 12X8", "stock" : 425, "price" : 10.36},
{"description": "SAB REXONA 12X8", "stock" : 389, "price" : 10.36},
{"description": "ESC DT ELET ORA", "stock" : 21, "price" : 84.21},
{"description": "ESC DT ELET ORA", "stock" : 52, "price" : 148.32},
{"description": "ESC DT ELET ORA", "stock" : 12, "price" : 74.32},
{"description": "ESC DT ELET ORA", "stock" : 35, "price" : 22.49},
{"description": "CARGA P/AP BARB", "stock" : 32, "price" : 12.47},
{"description": "SAB PALM NATURA", "stock" : 611, "price" : 18.82},
{"description": "SAB DOVE 12X90 ", "stock" : 43, "price" : 23.95},
{"description": "SAB FRANCIS CLA", "stock" : 1083, "price" : 15.10},
{"description": "SAB FRANCIS CLA", "stock" : 945, "price" : 15.10},
{"description": "SAB FRANCIS CLA", "stock" : 1308, "price" : 15.10},
{"description": "SAB FRANCIS CLA", "stock" : 1097, "price" : 15.10},
{"description": "SAB FRANCIS CLA", "stock" : 1022, "price" : 15.10},
{"description": "SAB FRANCIS CLA", "stock" : 1588, "price" : 15.10},
{"description": "SAB FRANCIS CLA", "stock" : 999, "price" : 15.10},
{"description": "CR DT COLG NEUT", "stock" : 111, "price" : 39.63},
{"description": "SH PALM NATURAL", "stock" : 74, "price" : 30.53},
{"description": "COND PALM NATUR", "stock" : 20, "price" : 35.89},
{"description": "SAB LIQ PALM NA", "stock" : 11, "price" : 13.42},
{"description": "SAB PALM NATURA", "stock" : 648, "price" : 18.82},
{"description": "SAB LIQ PROTEX ", "stock" : 33, "price" : 45.93},
{"description": "SAB LIQ PROTEX ", "stock" : 11, "price" : 34.45},
{"description": "AP BARB BIC 3 L", "stock" : 570, "price" : 26.50},
{"description": "AP BARB BIC 3 L", "stock" : 631, "price" : 26.50},
{"description": "AP BARB BIC SOL", "stock" : 69, "price" : 23.09},
{"description": "SAB LIQ PROTEX ", "stock" : 14, "price" : 13.63},
{"description": "SAB LIQ PROTEX ", "stock" : 7, "price" : 13.57},
{"description": "SAB LIQ PROTEX ", "stock" : 3, "price" : 13.57},
{"description": "ESMALTE IMPALA ", "stock" : 349, "price" : 13.65},
{"description": "MASCARA CONCENT", "stock" : 875, "price" : 10.03},
{"description": "CR DT COLG LUMI", "stock" : 167, "price" : 68.13},
{"description": "SAB PALM NATURA", "stock" : 497, "price" : 18.82},
{"description": "COND PALM NATUR", "stock" : 10, "price" : 35.91},
{"description": "ABS INTIMUS GEL", "stock" : 3, "price" : 156.99},
{"description": "CR TRAT TRESEMM", "stock" : 3, "price" : 14.84},
{"description": "ALCOOL GEL HIG ", "stock" : 61, "price" : 69.69},
{"description": "KIT SH + COND N", "stock" : 960, "price" : 7.42},
{"description": "SAB LIQ PALM NA", "stock" : 9, "price" : 9.50},
{"description": "ESC DT ORAL B I", "stock" : 15, "price" : 23.77},
{"description": "SAB REXONA 12X8", "stock" : 220, "price" : 10.36},
{"description": "SAB DOVE 12X90 ", "stock" : 110, "price" : 23.85},
{"description": "CR DT COLG TOTA", "stock" : 321, "price" : 85.16},
{"description": "CR DT COLG TOTA", "stock" : 3, "price" : 85.12},
{"description": "CR DT COLG TOTA", "stock" : 132, "price" : 85.14},
{"description": "SAB DOVE 12X90 ", "stock" : 31, "price" : 21.43},
{"description": "ABS MILI SUAVE ", "stock" : 31, "price" : 31.17},
{"description": "ABS MILI SUAVE ", "stock" : 58, "price" : 35.72},
{"description": "MASCARA CONCENT", "stock" : 826, "price" : 10.01},
{"description": "ABS MILI SUAVE ", "stock" : 62, "price" : 43.86},
{"description": "CR PENT SEDA 1K", "stock" : 1, "price" : 12.96},
{"description": "CR DT CLOSE-UP ", "stock" : 391, "price" : 14.29},
{"description": "CR PENT SEDA 1K", "stock" : 49, "price" : 13.09},
{"description": "FRALDA DESC COT", "stock" : 53, "price" : 108.00},
{"description": "FRALDA DESC COT", "stock" : 16, "price" : 112.88},
{"description": "FRALDA DESC GAL", "stock" : 806, "price" : 132.09},
{"description": "FRALDA DESC GAL", "stock" : 100, "price" : 134.36},
{"description": "FRALDA DESC GAL", "stock" : 722, "price" : 133.85},
{"description": "LENCO SOFTYS FO", "stock" : 89, "price" : 99.93},
{"description": "CR DT SORRISO X", "stock" : 29, "price" : 46.70},
{"description": "CR DT CLOSE-UP ", "stock" : 688, "price" : 14.31},
{"description": "CR DT CLOSE-UP ", "stock" : 544, "price" : 14.37},
{"description": "CR DT COLG SMIL", "stock" : 28, "price" : 83.14},
{"description": "CR DT SORRISO X", "stock" : 5, "price" : 46.51},
{"description": "ANT-SEPT BUC CO", "stock" : 2, "price" : 40.58},
{"description": "ABS INTIMUS DAY", "stock" : 1, "price" : 31.96},
{"description": "ABS INTIMUS DAY", "stock" : 36, "price" : 49.60},
{"description": "ABS INTIMUS DAY", "stock" : 145, "price" : 25.37},
{"description": "LENCO UMED HUGG", "stock" : 281, "price" : 5.16},
{"description": "SAB HUGGIES 12X", "stock" : 41, "price" : 15.08},
{"description": "SH HUGGIES 3X20", "stock" : 16, "price" : 14.00},
{"description": "ESMALTE IMPALA ", "stock" : 91, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 111, "price" : 11.05},
{"description": "ESMALTE IMPALA ", "stock" : 121, "price" : 11.05},
{"description": "ESMALTE IMPALA ", "stock" : 210, "price" : 11.05},
{"description": "ANT-SEPT BUC CO", "stock" : 3, "price" : 25.35},
{"description": "DESOD AERO SUAV", "stock" : 1, "price" : 71.20},
{"description": "DESOD AERO SUAV", "stock" : 6, "price" : 82.39},
{"description": "DESOD AERO SUAV", "stock" : 1, "price" : 70.68},
{"description": "DESOD AERO SUAV", "stock" : 13, "price" : 70.95},
{"description": "DESOD AERO SUAV", "stock" : 1, "price" : 71.01},
{"description": "SAB LIQ REXONA ", "stock" : 1, "price" : 1.74},
{"description": "DESOD AERO DOVE", "stock" : 1060, "price" : 122.82},
{"description": "DESOD AERO DOVE", "stock" : 2333, "price" : 122.99},
{"description": "CR TRAT NEUTROX", "stock" : 698, "price" : 8.80},
{"description": "ANT-SEPT BUC CO", "stock" : 2, "price" : 32.56},
{"description": "ANT-SEPT BUC CO", "stock" : 1, "price" : 40.58},
{"description": "SAB PALM NATURA", "stock" : 645, "price" : 10.72},
{"description": "SAB PALM NATURA", "stock" : 373, "price" : 10.72},
{"description": "SAB PALM NATURA", "stock" : 363, "price" : 10.72},
{"description": "SAB PALM NATURA", "stock" : 769, "price" : 10.72},
{"description": "SAB PALM NATURA", "stock" : 129, "price" : 10.72},
{"description": "SAB PALM NATURA", "stock" : 703, "price" : 10.71},
{"description": "SAB PALM NATURA", "stock" : 446, "price" : 10.72},
{"description": "SAB PALM NATURA", "stock" : 612, "price" : 10.72},
{"description": "SAB PALM NATURA", "stock" : 611, "price" : 10.72},
{"description": "SAB PALM NATURA", "stock" : 338, "price" : 10.71},
{"description": "SH PALM NATURAL", "stock" : 30, "price" : 30.58},
{"description": "COND PALM NATUR", "stock" : 18, "price" : 35.91},
{"description": "SAB PROTEX 12X8", "stock" : 41, "price" : 20.34},
{"description": "SAB PROTEX 12X8", "stock" : 59, "price" : 20.34},
{"description": "DESOD AERO DOVE", "stock" : 106, "price" : 122.78},
{"description": "ROUPA INTIMA DE", "stock" : 249, "price" : 26.28},
{"description": "ROUPA INTIMA DE", "stock" : 124, "price" : 26.28},
{"description": "FRALDA DESC HUG", "stock" : 326, "price" : 7.65},
{"description": "FRALDA DESC HUG", "stock" : 15, "price" : 13.05},
{"description": "FRALDA DESC HUG", "stock" : 10, "price" : 31.43},
{"description": "FRALDA DESC HUG", "stock" : 15, "price" : 4.56},
{"description": "FRALDA DESC HUG", "stock" : 4, "price" : 5.72},
{"description": "FRALDA DESC HUG", "stock" : 10, "price" : 4.56},
{"description": "FRALDA DESC HUG", "stock" : 13, "price" : 13.05},
{"description": "CR DT COLG TRIP", "stock" : 225, "price" : 25.46},
{"description": "CR DT COLG TRIP", "stock" : 159, "price" : 25.51},
{"description": "ESC DT SORRISO ", "stock" : 1, "price" : 5.21},
{"description": "ESC DT COLG 360", "stock" : 342, "price" : 13.53},
{"description": "SAB LIQ PROTEX ", "stock" : 4, "price" : 13.60},
{"description": "SAB LIQ PALM NU", "stock" : 14, "price" : 2.50},
{"description": "ESMALTE IMPALA ", "stock" : 89, "price" : 10.26},
{"description": "SAB ALBANY SUAV", "stock" : 1930, "price" : 8.47},
{"description": "SAB ALBANY SUAV", "stock" : 117, "price" : 8.47},
{"description": "SAB ALBANY SUAV", "stock" : 1225, "price" : 8.46},
{"description": "SAB ALBANY SUAV", "stock" : 1956, "price" : 8.47},
{"description": "SAB ALBANY SUAV", "stock" : 2370, "price" : 8.47},
{"description": "SAB ALBANY SUAV", "stock" : 1394, "price" : 8.48},
{"description": "DESOD AERO DOVE", "stock" : 96, "price" : 123.35},
{"description": "DESOD AERO DOVE", "stock" : 222, "price" : 124.17},
{"description": "DESOD AERO DOVE", "stock" : 247, "price" : 130.29},
{"description": "DESOD AERO DOVE", "stock" : 4, "price" : 118.81},
{"description": "DESOD AERO REXO", "stock" : 799, "price" : 7.63},
{"description": "DESOD ROLL-ON R", "stock" : 1, "price" : 17.50},
{"description": "REPELENTE EXPOS", "stock" : 17, "price" : 26.94},
{"description": "REPELENTE EXPOS", "stock" : 45, "price" : 26.97},
{"description": "REPELENTE EXPOS", "stock" : 12, "price" : 28.26},
{"description": "REPELENTE EXPOS", "stock" : 45, "price" : 49.36},
{"description": "KIT SH + COND N", "stock" : 1137, "price" : 7.43},
{"description": "CR DT COLG TOTA", "stock" : 75, "price" : 59.50},
{"description": "DESOD AERO REXO", "stock" : 156, "price" : 8.25},
{"description": "LENCO SOFTYS FO", "stock" : 1264, "price" : 15.80},
{"description": "CR DT CLOSE-UP ", "stock" : 319, "price" : 18.86},
{"description": "KIT SH + COND D", "stock" : 2296, "price" : 12.52},
{"description": "SAB PROTEX 12X8", "stock" : 479, "price" : 18.13},
{"description": "SAB PROTEX 12X8", "stock" : 452, "price" : 18.13},
{"description": "SAB PROTEX 12X8", "stock" : 545, "price" : 18.12},
{"description": "SAB PROTEX 12X8", "stock" : 571, "price" : 18.06},
{"description": "SAB REXONA 12X8", "stock" : 1050, "price" : 10.33},
{"description": "SAB PROTEX 12X8", "stock" : 330, "price" : 18.05},
{"description": "SAB PROTEX 12X8", "stock" : 386, "price" : 18.05},
{"description": "SAB PROTEX 12X8", "stock" : 277, "price" : 18.03},
{"description": "SAB PROTEX 12X8", "stock" : 263, "price" : 18.05},
{"description": "SAB PROTEX 12X8", "stock" : 641, "price" : 18.05},
{"description": "SAB PROTEX 12X8", "stock" : 253, "price" : 18.05},
{"description": "SAB PROTEX 12X8", "stock" : 238, "price" : 18.05},
{"description": "SAB PROTEX 12X8", "stock" : 338, "price" : 18.06},
{"description": "SAB PROTEX MEN ", "stock" : 9, "price" : 18.06},
{"description": "SAB PROTEX MEN ", "stock" : 108, "price" : 18.06},
{"description": "ESMALTE IMPALA ", "stock" : 177, "price" : 11.05},
{"description": "ESMALTE IMPALA ", "stock" : 95, "price" : 11.05},
{"description": "ESMALTE IMPALA ", "stock" : 109, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 131, "price" : 10.26},
{"description": "CR DT CLOSE-UP ", "stock" : 40, "price" : 30.55},
{"description": "CR DT CLOSE-UP ", "stock" : 109, "price" : 30.58},
{"description": "DESOD AERO ABOV", "stock" : 2809, "price" : 2.80},
{"description": "DESOD AERO ABOV", "stock" : 3775, "price" : 2.79},
{"description": "DESOD AERO ABOV", "stock" : 3494, "price" : 2.77},
{"description": "DESOD AERO ABOV", "stock" : 4165, "price" : 2.74},
{"description": "DESOD AERO ABOV", "stock" : 4, "price" : 2.63},
{"description": "DESOD AERO ABOV", "stock" : 1512, "price" : 2.77},
{"description": "ESPUMA BARB ABO", "stock" : 31, "price" : 4.37},
{"description": "ABS PLENITUDE F", "stock" : 60, "price" : 9.16},
{"description": "FRALDA DESC HUG", "stock" : 94, "price" : 12.62},
{"description": "CR DT COLG LUMI", "stock" : 2, "price" : 37.96},
{"description": "SAB LUX BOTANIC", "stock" : 3, "price" : 1.88},
{"description": "SAB LUX BOTANIC", "stock" : 2, "price" : 1.98},
{"description": "ABS INTIMUS SPO", "stock" : 3, "price" : 4.31},
{"description": "ABS INTIMUS SPO", "stock" : 89, "price" : 4.31},
{"description": "ANT-SEPT BUC CO", "stock" : 104, "price" : 17.76},
{"description": "SH TRESEMME 400", "stock" : 222, "price" : 7.11},
{"description": "SH TRESEMME 200", "stock" : 3, "price" : 4.75},
{"description": "SH TRESEMME 200", "stock" : 1, "price" : 4.75},
{"description": "SH TRESEMME 200", "stock" : 177, "price" : 3.59},
{"description": "CR TRAT TRESEMM", "stock" : 9, "price" : 8.25},
{"description": "COND CLEAR ANTI", "stock" : 136, "price" : 9.09},
{"description": "COND DOVE 200ML", "stock" : 48, "price" : 5.99},
{"description": "COND DOVE 200ML", "stock" : 240, "price" : 6.02},
{"description": "COND DOVE 200ML", "stock" : 123, "price" : 5.97},
{"description": "COND DOVE 200ML", "stock" : 274, "price" : 5.76},
{"description": "COND DOVE 400ML", "stock" : 246, "price" : 10.51},
{"description": "COND DOVE 400ML", "stock" : 192, "price" : 10.53},
{"description": "COND DOVE 400ML", "stock" : 2, "price" : 10.12},
{"description": "COND DOVE 400ML", "stock" : 9, "price" : 9.78},
{"description": "COND DOVE 400ML", "stock" : 138, "price" : 10.54},
{"description": "COND DOVE BABY ", "stock" : 207, "price" : 9.49},
{"description": "COND DOVE BABY ", "stock" : 84, "price" : 9.46},
{"description": "COND DOVE BABY ", "stock" : 318, "price" : 9.46},
{"description": "SH TRESEMME 400", "stock" : 63, "price" : 7.07},
{"description": "SH SEDA 325ML R", "stock" : 411, "price" : 4.31},
{"description": "SH SEDA 325ML P", "stock" : 1056, "price" : 4.33},
{"description": "SH SEDA 325ML L", "stock" : 3, "price" : 4.30},
{"description": "COND SEDA 325ML", "stock" : 1353, "price" : 5.57},
{"description": "COND SEDA 325ML", "stock" : 1019, "price" : 5.61},
{"description": "COND SEDA 325ML", "stock" : 1161, "price" : 5.56},
{"description": "COND SEDA 325ML", "stock" : 504, "price" : 5.60},
{"description": "COND SEDA 325ML", "stock" : 528, "price" : 5.56},
{"description": "COND SEDA 325ML", "stock" : 3, "price" : 5.54},
{"description": "COND SEDA 325ML", "stock" : 210, "price" : 5.56},
{"description": "COND SEDA 325ML", "stock" : 156, "price" : 5.58},
{"description": "COND TRESEMME 2", "stock" : 501, "price" : 6.87},
{"description": "COND TRESEMME 2", "stock" : 57, "price" : 5.82},
{"description": "COND TRESEMME 4", "stock" : 150, "price" : 8.35},
{"description": "COND TRESEMME 4", "stock" : 366, "price" : 8.35},
{"description": "COND TRESEMME 4", "stock" : 20, "price" : 8.37},
{"description": "COND TRESEMME 4", "stock" : 2, "price" : 8.37},
{"description": "COND TRESEMME 4", "stock" : 57, "price" : 8.35},
{"description": "CR PENT DOVE 20", "stock" : 210, "price" : 6.90},
{"description": "CR PENT TRESEMM", "stock" : 2, "price" : 7.65},
{"description": "FRALDA DESC HUG", "stock" : 1156, "price" : 19.31},
{"description": "FRALDA DESC HUG", "stock" : 547, "price" : 19.31},
{"description": "FRALDA DESC HUG", "stock" : 6, "price" : 19.31},
{"description": "FRALDA DESC HUG", "stock" : 834, "price" : 12.36},
{"description": "FRALDA DESC HUG", "stock" : 4, "price" : 12.36},
{"description": "FRALDA DESC HUG", "stock" : 410, "price" : 12.36},
{"description": "SAB FRANCIS PRO", "stock" : 2, "price" : -0.15},
{"description": "KIT SH + COND T", "stock" : 216, "price" : 10.47},
{"description": "KIT SH + COND T", "stock" : 21, "price" : 10.48},
{"description": "KIT SH + COND T", "stock" : 664, "price" : 10.46},
{"description": "KIT SH + COND T", "stock" : 459, "price" : 10.47},
{"description": "SAB LIQ PROTEX ", "stock" : 36, "price" : 2.29},
{"description": "SAB PROTEX INTI", "stock" : 300, "price" : 1.89},
{"description": "SAB PROTEX INTI", "stock" : 132, "price" : 1.89},
{"description": "ESC DT COLG KID", "stock" : 69, "price" : 8.68},
{"description": "DESOD AERO REXO", "stock" : 1, "price" : 7.62},
{"description": "DESOD AERO REXO", "stock" : 1956, "price" : 7.62},
{"description": "DESOD AERO REXO", "stock" : 2220, "price" : 7.62},
{"description": "DESOD AERO REXO", "stock" : 1, "price" : 7.62},
{"description": "DESOD AERO REXO", "stock" : 12, "price" : 7.62},
{"description": "DESOD AERO REXO", "stock" : 1980, "price" : 7.61},
{"description": "DESOD ROLL-ON R", "stock" : 6, "price" : 4.14},
{"description": "DESOD ROLL-ON R", "stock" : 174, "price" : 4.16},
{"description": "DESOD ROLL-ON S", "stock" : 360, "price" : 3.77},
{"description": "DESOD ROLL-ON S", "stock" : 259, "price" : 3.77},
{"description": "SAB LIQ LUX BOT", "stock" : 33, "price" : 1.69},
{"description": "SAB LIQ LUX BOT", "stock" : 54, "price" : 1.70},
{"description": "SAB LIQ LUX BOT", "stock" : 18, "price" : 1.69},
{"description": "SAB LIQ LUX BOT", "stock" : 62, "price" : 1.70},
{"description": "SAB LIQ LUX BOT", "stock" : 84, "price" : 1.70},
{"description": "SAB LIQ LUX BOT", "stock" : 24, "price" : 2.66},
{"description": "SAB LIQ LUX BOT", "stock" : 21, "price" : 2.67},
{"description": "SAB LIQ LUX BOT", "stock" : 84, "price" : 2.67},
{"description": "SAB LIQ LUX BOT", "stock" : 9, "price" : 2.66},
{"description": "SAB LUX BOTANIC", "stock" : 12, "price" : -0.19},
{"description": "SAB LUX BOTANIC", "stock" : 12, "price" : -0.19},
{"description": "SH CLEAR ANTIC ", "stock" : 24, "price" : 8.01},
{"description": "SH CLEAR ANTIC ", "stock" : 70, "price" : 7.96},
{"description": "SH CLEAR ANTIC ", "stock" : 303, "price" : 8.05},
{"description": "SH CLEAR ANTIC ", "stock" : 51, "price" : 7.87},
{"description": "SH CLEAR ANTIC ", "stock" : 513, "price" : 12.83},
{"description": "SH CLEAR MEN AN", "stock" : 440, "price" : 12.82},
{"description": "SH DOVE 200ML H", "stock" : 2, "price" : 4.82},
{"description": "SH DOVE MEN 200", "stock" : 204, "price" : 8.86},
{"description": "SH DOVE 400ML R", "stock" : 144, "price" : 8.77},
{"description": "SH DOVE 400ML R", "stock" : 93, "price" : 8.78},
{"description": "SH DOVE BABY 20", "stock" : 186, "price" : 5.31},
{"description": "SH SEDA 325ML B", "stock" : 6, "price" : 4.30},
{"description": "SH SEDA 325ML C", "stock" : 276, "price" : 4.29},
{"description": "SH SEDA 325ML H", "stock" : 1, "price" : 3.80},
{"description": "SH SEDA 325ML O", "stock" : 2334, "price" : 4.30},
{"description": "SH SEDA 325ML P", "stock" : 7, "price" : 4.32},
{"description": "SH CLEAR MEN AN", "stock" : 27, "price" : 7.97},
{"description": "SH DIMENSION A ", "stock" : 663, "price" : 9.40},
{"description": "SH DOVE 400ML H", "stock" : 105, "price" : 8.85},
{"description": "SH DOVE 400ML O", "stock" : 99, "price" : 8.63},
{"description": "SH DOVE 400ML R", "stock" : 230, "price" : 8.84},
{"description": "SH SEDA 325ML H", "stock" : 747, "price" : 4.33},
{"description": "SH SEDA 325ML L", "stock" : 9, "price" : 4.32},
{"description": "SH TRESEMME 200", "stock" : 277, "price" : 3.60},
{"description": "SH TRESEMME 400", "stock" : 213, "price" : 7.11},
{"description": "SH TRESEMME 400", "stock" : 126, "price" : 7.09},
{"description": "COND CLEAR ANTI", "stock" : 369, "price" : 9.59},
{"description": "COND DOVE 200ML", "stock" : 168, "price" : 5.98},
{"description": "COND DOVE 200ML", "stock" : 3, "price" : 5.73},
{"description": "COND DOVE 200ML", "stock" : 18, "price" : 5.98},
{"description": "COND SEDA 325ML", "stock" : 895, "price" : 5.60},
{"description": "COND SEDA 325ML", "stock" : 2, "price" : 5.55},
{"description": "COND SEDA 325ML", "stock" : 540, "price" : 5.62},
{"description": "COND SEDA 325ML", "stock" : 119, "price" : 5.61},
{"description": "COND TRESEMME 2", "stock" : 358, "price" : 5.82},
{"description": "COND TRESEMME 2", "stock" : 378, "price" : 4.45},
{"description": "COND TRESEMME 4", "stock" : 148, "price" : 8.35},
{"description": "ABS LADYSOFT NO", "stock" : 288, "price" : 0.63},
{"description": "ABS LADYSOFT NO", "stock" : 2052, "price" : 8.31},
{"description": "ABS LADYSOFT NO", "stock" : 3192, "price" : 1.42},
{"description": "ABS LADYSOFT NO", "stock" : 1344, "price" : 1.12},
{"description": "LENCO SOFTYS FO", "stock" : 3534, "price" : 0.24},
{"description": "ABS INTIMUS GEL", "stock" : 12, "price" : 1.63},
{"description": "ABS INTIMUS GEL", "stock" : 7, "price" : 1.63},
{"description": "ABS MILI SECA T", "stock" : 1716, "price" : 0.50},
{"description": "ABS MILI SUAVE ", "stock" : 696, "price" : 0.65},
{"description": "ABS MILI SUAVE ", "stock" : 528, "price" : 0.36},
{"description": "ALICATE CUT MUN", "stock" : 159, "price" : 3.34},
{"description": "ALICATE CUT MUN", "stock" : 4, "price" : 9.89},
{"description": "ALICATE CUT MUN", "stock" : 2297, "price" : 2.88},
{"description": "BRONZEADOR OLEO", "stock" : 150, "price" : 6.79},
{"description": "BRONZEADOR OLEO", "stock" : 95, "price" : 6.79},
{"description": "SH CLEAR ANTIC ", "stock" : 150, "price" : 10.50},
{"description": "SH CLEAR MEN AN", "stock" : 879, "price" : 10.45},
{"description": "CR DT CLOSE-UP ", "stock" : 744, "price" : 1.87},
{"description": "SAB LIQ PALM NA", "stock" : 2, "price" : 3.41},
{"description": "COLONIA HUGGIES", "stock" : 543, "price" : 4.75},
{"description": "COND HUGGIES 20", "stock" : 102, "price" : 5.44},
{"description": "CR PENT KOLENE ", "stock" : 1296, "price" : 1.06},
{"description": "CR PENT KOLENE ", "stock" : 1356, "price" : 3.82},
{"description": "CR PENT KOLENE ", "stock" : 1012, "price" : 2.80},
{"description": "CR PENT KOLENE ", "stock" : 246, "price" : 2.82},
{"description": "CR PENT KOLENE ", "stock" : 592, "price" : 2.45},
{"description": "COND NEUTROX 10", "stock" : 1260, "price" : 1.06},
{"description": "COND NEUTROX 50", "stock" : 831, "price" : 4.75},
{"description": "COND NIELY GOLD", "stock" : 339, "price" : 3.98},
{"description": "COND NIELY GOLD", "stock" : 243, "price" : 3.98},
{"description": "COND NIELY GOLD", "stock" : 435, "price" : 3.98},
{"description": "CR PENT DOVE 20", "stock" : 267, "price" : 6.94},
{"description": "CR PENT NEUTROX", "stock" : 1299, "price" : 3.18},
{"description": "CR PENT NEUTROX", "stock" : 321, "price" : 3.18},
{"description": "CR PENT NIELY G", "stock" : 1, "price" : 7.02},
{"description": "CR PENT NIELY G", "stock" : 756, "price" : 2.98},
{"description": "CR PENT NIELY G", "stock" : 399, "price" : 2.98},
{"description": "CR PENT NIELY G", "stock" : 492, "price" : 2.99},
{"description": "CR PENT NIELY G", "stock" : 702, "price" : 2.99},
{"description": "CR PENT PALM NA", "stock" : 258, "price" : 3.06},
{"description": "CR PENT PALM NA", "stock" : 23, "price" : 3.06},
{"description": "CR PENT SEDA 29", "stock" : 36, "price" : 4.43},
{"description": "DESOD AERO BRUT", "stock" : 6, "price" : 2.45},
{"description": "DESOD AERO BRUT", "stock" : 4, "price" : 3.26},
{"description": "CR PENT SEDA 29", "stock" : 63, "price" : 4.44},
{"description": "CR PENT SEDA 30", "stock" : 150, "price" : 4.31},
{"description": "CR PENT SEDA 30", "stock" : 3, "price" : 4.35},
{"description": "CR PENT SEDA 30", "stock" : 2, "price" : 4.29},
{"description": "CR PENT SEDA 30", "stock" : 1347, "price" : 4.31},
{"description": "CR PENT SEDA 30", "stock" : 888, "price" : 4.30},
{"description": "CR PENT SEDA 30", "stock" : 714, "price" : 4.33},
{"description": "CR PENT TRESEMM", "stock" : 2, "price" : 4.94},
{"description": "CR TRAT DOVE 35", "stock" : 21, "price" : 9.40},
{"description": "CR TRAT NEUTROX", "stock" : 279, "price" : 7.78},
{"description": "CR TRAT NIELY G", "stock" : 1, "price" : 3.76},
{"description": "CR TRAT NIELY G", "stock" : 165, "price" : 6.25},
{"description": "CR TRAT NIELY G", "stock" : 156, "price" : 6.25},
{"description": "CR TRAT NIELY G", "stock" : 123, "price" : 6.25},
{"description": "CR TRAT NIELY G", "stock" : 54, "price" : 6.25},
{"description": "CR TRAT TRESEMM", "stock" : 15, "price" : 8.25},
{"description": "CR TRAT TRESEMM", "stock" : 9, "price" : 8.25},
{"description": "CR TRAT TRESEMM", "stock" : 6, "price" : 8.25},
{"description": "DESCOLORANTE PO", "stock" : 252, "price" : 0.82},
{"description": "DESCOLORANTE PO", "stock" : 1153, "price" : 2.54},
{"description": "DESCOLORANTE PO", "stock" : 1164, "price" : 2.06},
{"description": "DESCOLORANTE PO", "stock" : 4200, "price" : -0.05},
{"description": "DESCOLORANTE PO", "stock" : 12, "price" : 0.12},
{"description": "DESCOLORANTE PO", "stock" : 480, "price" : 1.03},
{"description": "DESCOLORANTE PO", "stock" : 1032, "price" : 2.95},
{"description": "DESCOLORANTE PO", "stock" : 1324, "price" : 0.23},
{"description": "DESOD AERO REXO", "stock" : 3, "price" : 7.64},
{"description": "DESOD AERO REXO", "stock" : 1422, "price" : 7.62},
{"description": "DESOD AERO REXO", "stock" : 6, "price" : 5.67},
{"description": "DESOD AERO REXO", "stock" : 240, "price" : 7.65},
{"description": "DESOD CR ALMA F", "stock" : 169, "price" : 3.72},
{"description": "DESOD ROLL-ON A", "stock" : 204, "price" : 4.08},
{"description": "DESOD ROLL-ON S", "stock" : 126, "price" : 4.08},
{"description": "DESOD ROLL-ON S", "stock" : 24, "price" : 4.08},
{"description": "DESOD SPRAY ALM", "stock" : 1056, "price" : 2.10},
{"description": "DESOD SPRAY ALM", "stock" : 900, "price" : 2.09},
{"description": "ESC DT COLG ESS", "stock" : 7104, "price" : 0.80},
{"description": "ESC DT COLG PRO", "stock" : 1, "price" : 7.83},
{"description": "ESC DT SORRISO ", "stock" : 1, "price" : 6.39},
{"description": "REPELENTE AERO ", "stock" : 19, "price" : 11.48},
{"description": "FITA DENTAL COL", "stock" : 251, "price" : 8.40},
{"description": "DESOD CR REXONA", "stock" : 111, "price" : 21.18},
{"description": "COND DOVE 170ML", "stock" : 198, "price" : 11.37},
{"description": "COND DOVE 170ML", "stock" : 92, "price" : 11.37},
{"description": "COND DOVE 170ML", "stock" : 4, "price" : 11.41},
{"description": "GEL TRESEMME 20", "stock" : 528, "price" : 3.90},
{"description": "LEITE DE ROSAS ", "stock" : 6, "price" : 3.97},
{"description": "LEITE DE ROSAS ", "stock" : 6, "price" : 2.15},
{"description": "LEITE DE ROSAS ", "stock" : 400, "price" : 1.25},
{"description": "LEITE DE ROSAS ", "stock" : 1, "price" : 0.57},
{"description": "LENCO UMED MILI", "stock" : 348, "price" : 2.06},
{"description": "LENCO UMED MILI", "stock" : 372, "price" : 1.28},
{"description": "SH SUAVE 325ML ", "stock" : 117, "price" : 2.11},
{"description": "SH SUAVE 325ML ", "stock" : 87, "price" : 2.12},
{"description": "SH SUAVE 325ML ", "stock" : 213, "price" : 2.12},
{"description": "DESOD AERO DOVE", "stock" : 40, "price" : 122.92},
{"description": "DESOD AERO DOVE", "stock" : 111, "price" : 128.06},
{"description": "DESOD AERO DOVE", "stock" : 25, "price" : 121.98},
{"description": "DESOD AERO DOVE", "stock" : 13, "price" : 94.56},
{"description": "PRESERVATIVO PR", "stock" : 444, "price" : 1.74},
{"description": "PRESERVATIVO PR", "stock" : 12, "price" : 2.81},
{"description": "REPELENTE OFF D", "stock" : 32, "price" : 17.59},
{"description": "REPELENTE OFF F", "stock" : 8, "price" : 3.58},
{"description": "REPELENTE OFF F", "stock" : 546, "price" : 6.32},
{"description": "SAB LIQ GRANADO", "stock" : 309, "price" : 9.12},
{"description": "SAB LIQ HUGGIES", "stock" : 22, "price" : 5.92},
{"description": "ABS INTIMUS GEL", "stock" : 6, "price" : 9.95},
{"description": "ABS INTIMUS GEL", "stock" : 270, "price" : 4.63},
{"description": "ABS INTIMUS GEL", "stock" : 584, "price" : 1.93},
{"description": "ABS INTIMUS GEL", "stock" : 1489, "price" : 0.67},
{"description": "ABS INTIMUS GEL", "stock" : 1446, "price" : 1.93},
{"description": "SH GRANADO BEBE", "stock" : 21, "price" : 9.65},
{"description": "SH NIELY GOLD 2", "stock" : 585, "price" : 4.10},
{"description": "SH NIELY GOLD 2", "stock" : 492, "price" : 4.10},
{"description": "SILICONE NIELY ", "stock" : 342, "price" : 7.32},
{"description": "SILICONE NIELY ", "stock" : 102, "price" : 7.32},
{"description": "SILICONE NIELY ", "stock" : 229, "price" : 7.36},
{"description": "SPRAY SECANTE F", "stock" : 243, "price" : 5.66},
{"description": "TALCO ALMA DE F", "stock" : 171, "price" : 5.73},
{"description": "TALCO BARLA PEQ", "stock" : 4716, "price" : 1.70},
{"description": "TINT COR&TON 13", "stock" : 357, "price" : 4.71},
{"description": "TINT COR&TON 13", "stock" : 444, "price" : 4.71},
{"description": "TINT COR&TON 13", "stock" : 885, "price" : 4.70},
{"description": "TINT COR&TON 13", "stock" : 102, "price" : 4.71},
{"description": "TINT COR&TON 13", "stock" : 345, "price" : 4.73},
{"description": "TINT COR&TON 13", "stock" : 807, "price" : 4.70},
{"description": "TINT COR&TON 13", "stock" : 850, "price" : 4.70},
{"description": "TINT COR&TON 13", "stock" : 135, "price" : 4.71},
{"description": "TINT COR&TON 13", "stock" : 669, "price" : 4.71},
{"description": "TINT COR&TON 13", "stock" : 121, "price" : 4.71},
{"description": "TINT COR&TON 13", "stock" : 180, "price" : 4.71},
{"description": "TINT COR&TON 13", "stock" : 300, "price" : 4.71},
{"description": "TINT COR&TON 13", "stock" : 222, "price" : 4.71},
{"description": "TINT COR&TON 13", "stock" : 18, "price" : 4.71},
{"description": "TINT COR&TON 13", "stock" : 66, "price" : 4.71},
{"description": "TINT COR&TON 13", "stock" : 411, "price" : 4.71},
{"description": "TINT COR&TON 13", "stock" : 168, "price" : 4.71},
{"description": "TINT COR&TON 13", "stock" : 237, "price" : 4.71},
{"description": "TINT COR&TON 13", "stock" : 393, "price" : 4.71},
{"description": "TINT COR&TON 13", "stock" : 43, "price" : 4.71},
{"description": "TINT COR&TON 13", "stock" : 501, "price" : 4.71},
{"description": "TINT COR&TON 13", "stock" : 6, "price" : 4.71},
{"description": "TINT COR&TON 13", "stock" : 102, "price" : 4.71},
{"description": "TINT COR&TON 13", "stock" : 144, "price" : 4.71},
{"description": "TINT COR&TON 13", "stock" : 99, "price" : 4.71},
{"description": "TINT COR&TON 13", "stock" : 168, "price" : 4.71},
{"description": "TINT COR&TON 13", "stock" : 6, "price" : 4.73},
{"description": "TINT COR&TON 13", "stock" : 111, "price" : 4.73},
{"description": "TINT COR&TON 13", "stock" : 2046, "price" : 4.68},
{"description": "TINT COR&TON 13", "stock" : 1531, "price" : 4.69},
{"description": "TINT COR&TON 13", "stock" : 712, "price" : 4.72},
{"description": "TINT COR&TON 13", "stock" : 157, "price" : 4.71},
{"description": "TINT COR&TON 13", "stock" : 165, "price" : 4.71},
{"description": "TINT COR&TON 13", "stock" : 219, "price" : 4.71},
{"description": "ESMALTE IMPALA ", "stock" : 43, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 256, "price" : 11.05},
{"description": "ESMALTE IMPALA ", "stock" : 171, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 128, "price" : 11.05},
{"description": "PRESERVATIVO PR", "stock" : 84, "price" : 2.75},
{"description": "PRESERVATIVO PR", "stock" : 840, "price" : 1.69},
{"description": "PRESERVATIVO PR", "stock" : 1440, "price" : 1.69},
{"description": "PRESERVATIVO PR", "stock" : 1092, "price" : 2.76},
{"description": "PRESERVATIVO PR", "stock" : 696, "price" : 3.17},
{"description": "PRESERVATIVO PR", "stock" : 936, "price" : 1.69},
{"description": "PRESERVATIVO PR", "stock" : 672, "price" : 3.47},
{"description": "PRESERVATIVO PR", "stock" : 1440, "price" : 1.07},
{"description": "PRESERVATIVO PR", "stock" : 324, "price" : 2.69},
{"description": "PRESERVATIVO PR", "stock" : 1632, "price" : 1.69},
{"description": "PRESERVATIVO PR", "stock" : 300, "price" : 6.27},
{"description": "PRESERVATIVO PR", "stock" : 1416, "price" : 1.69},
{"description": "PRESERVATIVO PR", "stock" : 408, "price" : 2.54},
{"description": "PRESERVATIVO PR", "stock" : 1092, "price" : 2.18},
{"description": "PRESERVATIVO PR", "stock" : 1008, "price" : 1.69},
{"description": "SAB LIQ PALM NA", "stock" : 1, "price" : 1.41},
{"description": "SAB LIQ PALM NA", "stock" : 988, "price" : 1.42},
{"description": "SAB LIQ PROTEX ", "stock" : 63, "price" : 2.17},
{"description": "COND DOVE 400ML", "stock" : 285, "price" : 11.81},
{"description": "DESOD AERO REXO", "stock" : 504, "price" : 7.57},
{"description": "CR DT CLOSE-UP ", "stock" : 99, "price" : 18.78},
{"description": "SAB LIQ REXONA ", "stock" : 213, "price" : 2.63},
{"description": "SAB LIQ REXONA ", "stock" : 198, "price" : 2.63},
{"description": "SAB DOVE 12X90 ", "stock" : 74, "price" : 21.42},
{"description": "SAB LIQ DOVE 20", "stock" : 78, "price" : 3.71},
{"description": "DESOD AERO REXO", "stock" : 300, "price" : 8.09},
{"description": "TALCO REXONA 10", "stock" : 243, "price" : 5.51},
{"description": "TALCO REXONA 10", "stock" : 198, "price" : 5.54},
{"description": "ANT-SEPT BUC CO", "stock" : 991, "price" : 4.67},
{"description": "CR DT SORRISO F", "stock" : 70, "price" : 29.27},
{"description": "ESC DT SORRISO ", "stock" : 325, "price" : 5.24},
{"description": "SAB LIQ PROTEX ", "stock" : 29, "price" : 3.85},
{"description": "COND PALM NATUR", "stock" : 18, "price" : 4.32},
{"description": "SH PALM NATURAL", "stock" : 1, "price" : 2.72},
{"description": "SH PALM NATURAL", "stock" : 3, "price" : 3.78},
{"description": "ANT-SEPT BUC CO", "stock" : 997, "price" : 4.67},
{"description": "SH DOVE 400ML R", "stock" : 84, "price" : 8.78},
{"description": "CR DT CLOSE-UP ", "stock" : 360, "price" : 1.66},
{"description": "SAB LIQ DOVE 20", "stock" : 93, "price" : 3.75},
{"description": "SAB LIQ DOVE 20", "stock" : 1, "price" : 3.73},
{"description": "SAB LIQ LIFEBUO", "stock" : 204, "price" : 2.85},
{"description": "SAB LIQ LIFEBUO", "stock" : 1, "price" : 2.85},
{"description": "ESMALTE IMPALA ", "stock" : 253, "price" : 12.25},
{"description": "ESMALTE IMPALA ", "stock" : 224, "price" : 13.11},
{"description": "ESMALTE IMPALA ", "stock" : 139, "price" : 13.12},
{"description": "ESMALTE IMPALA ", "stock" : 142, "price" : 12.19},
{"description": "ESMALTE IMPALA ", "stock" : 145, "price" : 13.12},
{"description": "DESOD AERO REXO", "stock" : 12, "price" : 7.64},
{"description": "DESOD AERO AXE ", "stock" : 168, "price" : 8.60},
{"description": "DESOD AERO AXE ", "stock" : 11, "price" : 8.62},
{"description": "COND TRESEMME 1", "stock" : 532, "price" : 9.68},
{"description": "COND TRESEMME 1", "stock" : 477, "price" : 9.70},
{"description": "COND SEDA 325ML", "stock" : 1078, "price" : 5.56},
{"description": "SH SEDA 325ML L", "stock" : 294, "price" : 4.29},
{"description": "COND DOVE 400ML", "stock" : 132, "price" : 10.12},
{"description": "COND DOVE 400ML", "stock" : 1, "price" : 10.16},
{"description": "SH DOVE MEN CAR", "stock" : 561, "price" : 19.61},
{"description": "SH DOVE 400ML H", "stock" : 124, "price" : 8.78},
{"description": "REPELENTE EXPOS", "stock" : 34, "price" : 12.55},
{"description": "REPELENTE EXPOS", "stock" : 82, "price" : 12.55},
{"description": "ESMALTE IMPALA ", "stock" : 134, "price" : 13.64},
{"description": "ESMALTE IMPALA ", "stock" : 134, "price" : 13.64},
{"description": "ESMALTE IMPALA ", "stock" : 163, "price" : 13.64},
{"description": "SAB FRANCIS ARO", "stock" : 13272, "price" : -0.09},
{"description": "SAB FRANCIS ARO", "stock" : 13260, "price" : -0.09},
{"description": "SAB FRANCIS ARO", "stock" : 15144, "price" : -0.09},
{"description": "SAB FRANCIS ARO", "stock" : 12828, "price" : -0.09},
{"description": "SAB FRANCIS ARO", "stock" : 13704, "price" : -0.09},
{"description": "SAB FRANCIS ARO", "stock" : 15672, "price" : -0.09},
{"description": "SAB FRANCIS ARO", "stock" : 15408, "price" : -0.09},
{"description": "SAB FRANCIS ARO", "stock" : 13644, "price" : -0.09},
{"description": "CR P/CABELO TRI", "stock" : 48, "price" : 7.05},
{"description": "ESC DT COLG KID", "stock" : 564, "price" : 4.35},
{"description": "SH DOVE 400ML O", "stock" : 153, "price" : 8.84},
{"description": "PRESERVATIVO PR", "stock" : 672, "price" : 2.05},
{"description": "PRESERVATIVO PR", "stock" : 624, "price" : 3.17},
{"description": "PRESERVATIVO PR", "stock" : 408, "price" : 1.69},
{"description": "SAB ALMA FLORES", "stock" : 147, "price" : 20.20},
{"description": "AP BARB BIC COM", "stock" : 3396, "price" : 1.35},
{"description": "FRALDA DESC HUG", "stock" : 6, "price" : 20.36},
{"description": "ANT-SEPT BUC CO", "stock" : 81, "price" : 25.35},
{"description": "KIT SH + COND P", "stock" : 134, "price" : 8.76},
{"description": "FRALDA DESC HUG", "stock" : 35, "price" : 20.36},
{"description": "DESOD AERO ABOV", "stock" : 2057, "price" : 2.70},
{"description": "DESOD AERO ABOV", "stock" : 828, "price" : 2.70},
{"description": "FRALDA DESC GAL", "stock" : 11, "price" : 79.33},
{"description": "DESOD AERO ABOV", "stock" : 646, "price" : 2.61},
{"description": "DESOD AERO ABOV", "stock" : 6309, "price" : 2.76},
{"description": "FRALDA DESC HUG", "stock" : 184, "price" : 17.94},
{"description": "FRALDA DESC HUG", "stock" : 46, "price" : 19.32},
{"description": "SH PALM NATUREZ", "stock" : 6, "price" : 4.25},
{"description": "SILICONE NIELY ", "stock" : 317, "price" : 7.35},
{"description": "COND KOLENE 300", "stock" : 951, "price" : 3.60},
{"description": "SH KOLENE 300ML", "stock" : 1183, "price" : 3.17},
{"description": "CR TRAT KOLENE ", "stock" : 952, "price" : 7.12},
{"description": "PROTETOR SOLAR ", "stock" : 345, "price" : 18.34},
{"description": "AP BARB BIC COM", "stock" : 2282, "price" : 4.26},
{"description": "CR DT COLG SENS", "stock" : 504, "price" : 10.35},
{"description": "CR DT COLG SENS", "stock" : 528, "price" : 10.52},
{"description": "ANT-SEPT BUC CO", "stock" : 15, "price" : 10.18},
{"description": "OLEO FARMAX 100", "stock" : 696, "price" : 1.44},
{"description": "OLEO FARMAX 100", "stock" : 1128, "price" : 1.44},
{"description": "OLEO FARMAX 100", "stock" : 996, "price" : 1.44},
{"description": "OLEO FARMAX 100", "stock" : 756, "price" : 1.44},
{"description": "OLEO FARMAX 100", "stock" : 1116, "price" : 1.80},
{"description": "OLEO FARMAX 100", "stock" : 600, "price" : 1.82},
{"description": "OLEO FARMAX 100", "stock" : 300, "price" : 1.64},
{"description": "OLEO FARMAX 100", "stock" : 480, "price" : 1.44},
{"description": "SH NEUTROX 300M", "stock" : 1230, "price" : 3.42},
{"description": "SH NEUTROX 300M", "stock" : 498, "price" : 3.46},
{"description": "COND NEUTROX 30", "stock" : 378, "price" : 3.93},
{"description": "COND NEUTROX 30", "stock" : 207, "price" : 3.95},
{"description": "COND NEUTROX 20", "stock" : 468, "price" : 2.22},
{"description": "COND NEUTROX 20", "stock" : 294, "price" : 2.23},
{"description": "DESOD AERO ABOV", "stock" : 2737, "price" : 2.69},
{"description": "DESOD AERO ABOV", "stock" : 2126, "price" : 2.69},
{"description": "ESMALTE IMPALA ", "stock" : 45, "price" : 13.12},
{"description": "ESMALTE IMPALA ", "stock" : 67, "price" : 13.12},
{"description": "ESMALTE IMPALA ", "stock" : 3, "price" : 12.20},
{"description": "ESMALTE IMPALA ", "stock" : 69, "price" : 13.11},
{"description": "ANT-SEPT BUC CO", "stock" : 15, "price" : 7.78},
{"description": "OLEO CAPILAR NI", "stock" : 990, "price" : 3.66},
{"description": "KIT SH + COND N", "stock" : 1031, "price" : 7.42},
{"description": "CR TRAT NIELY G", "stock" : 147, "price" : 6.25},
{"description": "CR PENT NIELY G", "stock" : 396, "price" : 2.98},
{"description": "TINT COR&TON 13", "stock" : 1746, "price" : 4.70},
{"description": "FRALDA DESC GAL", "stock" : 314, "price" : 132.43},
{"description": "COND SEDA 170ML", "stock" : 13, "price" : 6.23},
{"description": "DESOD CR REXONA", "stock" : 321, "price" : 21.26},
{"description": "COND SEDA 170ML", "stock" : 516, "price" : 6.23},
{"description": "COND SEDA 170ML", "stock" : 33, "price" : 6.22},
{"description": "CR DT SORRISO K", "stock" : 74, "price" : 42.24},
{"description": "FRALDA DESC GAL", "stock" : 197, "price" : 17.13},
{"description": "FRALDA DESC GAL", "stock" : 1, "price" : 16.07},
{"description": "DESOD CR SUAVE ", "stock" : 612, "price" : 1.24},
{"description": "DESOD AERO REXO", "stock" : 1128, "price" : 7.63},
{"description": "DESOD CR SUAVE ", "stock" : 636, "price" : 1.24},
{"description": "FRALDA DESC GAL", "stock" : 1, "price" : 14.23},
{"description": "FRALDA DESC GAL", "stock" : 4, "price" : 13.17},
{"description": "CR TRAT NEUTROX", "stock" : 347, "price" : 4.88},
{"description": "CR TRAT NEUTROX", "stock" : 211, "price" : 7.94},
{"description": "CR TRAT NEUTROX", "stock" : 183, "price" : 4.88},
{"description": "SH NEUTROX 300M", "stock" : 690, "price" : 3.47},
{"description": "COND NEUTROX 30", "stock" : 462, "price" : 3.93},
{"description": "CR TRAT NEUTROX", "stock" : 341, "price" : 8.80},
{"description": "CR TRAT NEUTROX", "stock" : 420, "price" : 4.91},
{"description": "COND PALM NATUR", "stock" : 420, "price" : 5.15},
{"description": "PRESERVATIVO PR", "stock" : 408, "price" : 4.10},
{"description": "DESOD AERO REXO", "stock" : 1188, "price" : 8.21},
{"description": "ESC DT COLG TWI", "stock" : 961, "price" : 7.32},
{"description": "SAB FRANCIS CLA", "stock" : 1050, "price" : 15.10},
{"description": "DESOD AERO FRAN", "stock" : 1338, "price" : 4.29},
{"description": "DESOD AERO FRAN", "stock" : 1167, "price" : 4.29},
{"description": "DESOD AERO FRAN", "stock" : 198, "price" : 4.39},
{"description": "DESOD AERO FRAN", "stock" : 84, "price" : 4.39},
{"description": "DESOD AERO FRAN", "stock" : 77, "price" : 4.29},
{"description": "DESOD AERO REXO", "stock" : 9, "price" : 7.62},
{"description": "ALICATE CUT MUN", "stock" : 282, "price" : 19.86},
{"description": "SAB REXONA 12X8", "stock" : 127, "price" : 10.36},
{"description": "CR DT COLG NATU", "stock" : 22, "price" : 59.63},
{"description": "CR DT COLG NATU", "stock" : 90, "price" : 59.64},
{"description": "SAB PALM KIDS M", "stock" : 369, "price" : 16.66},
{"description": "SAB LIQ PALM KI", "stock" : 2, "price" : 7.11},
{"description": "SAB LIQ PALM KI", "stock" : 11, "price" : 4.02},
{"description": "ESC DT COLG CLA", "stock" : 804, "price" : 1.54},
{"description": "ESC DT COLG CLA", "stock" : 1752, "price" : 1.54},
{"description": "ESC DT COLG EXT", "stock" : 2544, "price" : 3.90},
{"description": "ESC DT COLG SMI", "stock" : 27, "price" : 12.11},
{"description": "LENCO SOFTYS FO", "stock" : 450, "price" : 1.22},
{"description": "SAB PROTEX 6X12", "stock" : 2, "price" : 11.58},
{"description": "SAB PROTEX 6X12", "stock" : 10, "price" : 11.59},
{"description": "SAB PROTEX 6X12", "stock" : 23, "price" : 11.58},
{"description": "LEITE COLONIA 2", "stock" : 2, "price" : 2.82},
{"description": "LEITE COLONIA 1", "stock" : 6, "price" : 1.58},
{"description": "LEITE COLONIA 1", "stock" : 96, "price" : 1.59},
{"description": "LEITE COLONIA 1", "stock" : 576, "price" : 1.82},
{"description": "LEITE COLONIA 2", "stock" : 12, "price" : 2.84},
{"description": "LOCAO HIDR MONA", "stock" : 3, "price" : 2.58},
{"description": "LOCAO HIDR PAIX", "stock" : 5, "price" : 4.91},
{"description": "ABS INTIMUS DAY", "stock" : 1716, "price" : 1.20},
{"description": "FRALDA DESC HUG", "stock" : 347, "price" : 37.49},
{"description": "FRALDA DESC HUG", "stock" : 269, "price" : 37.49},
{"description": "OLEO MINERAL BE", "stock" : 33, "price" : 1.46},
{"description": "OLEO MINERAL BE", "stock" : 180, "price" : 1.64},
{"description": "OLEO MINERAL BE", "stock" : 24, "price" : 1.55},
{"description": "OLEO MINERAL BE", "stock" : 48, "price" : 1.50},
{"description": "ABS INTIMUS DAY", "stock" : 696, "price" : 3.39},
{"description": "ABS INTIMUS DAY", "stock" : 172, "price" : 7.43},
{"description": "CR CONTRA ASSAD", "stock" : 5, "price" : 7.22},
{"description": "CR DT CLOSE-UP ", "stock" : 732, "price" : 1.05},
{"description": "SAB REXONA 12X8", "stock" : 195, "price" : 10.41},
{"description": "REPELENTE OFF F", "stock" : 464, "price" : 6.94},
{"description": "LOCAO HID DOVE ", "stock" : 45, "price" : 7.36},
{"description": "LOCAO HID VASEN", "stock" : 186, "price" : 7.47},
{"description": "SAB DOVE MEN CA", "stock" : 65, "price" : 21.43},
{"description": "SAB DOVE 12X90 ", "stock" : 36, "price" : 21.43},
{"description": "CR PENT SEDA 40", "stock" : 270, "price" : 7.65},
{"description": "CR PENT SEDA 40", "stock" : 264, "price" : 7.33},
{"description": "CR TRAT MASCARA", "stock" : 9, "price" : 5.84},
{"description": "CR TRAT MASCARA", "stock" : 48, "price" : 5.84},
{"description": "CR TRAT MASCARA", "stock" : 3, "price" : 5.85},
{"description": "LENCO UMED NEVE", "stock" : 2, "price" : 4.53},
{"description": "SH SEDA 325ML B", "stock" : 24, "price" : 4.32},
{"description": "COND SEDA 325ML", "stock" : 942, "price" : 5.60},
{"description": "ESC DT COLG ULT", "stock" : 36, "price" : 15.86},
{"description": "ESC DT COLG ULT", "stock" : 24, "price" : 32.44},
{"description": "COND PALM NATUR", "stock" : 24, "price" : 5.15},
{"description": "CR PENT PALM NA", "stock" : 318, "price" : 3.06},
{"description": "CR PENT PALM NA", "stock" : 336, "price" : 3.06},
{"description": "ESC DT COLG CLA", "stock" : 356, "price" : 12.85},
{"description": "SAB LIQ GRANADO", "stock" : 360, "price" : 9.12},
{"description": "SAB LIQ GRANADO", "stock" : 330, "price" : 9.12},
{"description": "SAB LIQ GRANADO", "stock" : 126, "price" : 6.55},
{"description": "SH GRANADO BEBE", "stock" : 45, "price" : 9.65},
{"description": "SH GRANADO BEBE", "stock" : 72, "price" : 9.65},
{"description": "COND GRANADO BE", "stock" : 36, "price" : 11.66},
{"description": "COND GRANADO BE", "stock" : 99, "price" : 11.66},
{"description": "SAB GRANADO GLI", "stock" : 142, "price" : 32.41},
{"description": "LENCO UMED GRAN", "stock" : 55, "price" : 5.90},
{"description": "SAB LIQ PHEBO G", "stock" : 42, "price" : 9.18},
{"description": "SAB LIQ PHEBO G", "stock" : 21, "price" : 9.18},
{"description": "SAB LIQ PHEBO G", "stock" : 51, "price" : 9.18},
{"description": "SAB LIQ PHEBO G", "stock" : 58, "price" : 9.18},
{"description": "SAB LIQ PHEBO G", "stock" : 54, "price" : 9.18},
{"description": "DESOD SPRAY PHE", "stock" : 442, "price" : 2.77},
{"description": "DESOD SPRAY PHE", "stock" : 144, "price" : 2.77},
{"description": "DESOD SPRAY PHE", "stock" : 156, "price" : 2.77},
{"description": "DESOD SPRAY PHE", "stock" : 144, "price" : 2.77},
{"description": "DESOD SPRAY PHE", "stock" : 144, "price" : 2.77},
{"description": "COLONIA PHEBO 2", "stock" : 52, "price" : 34.27},
{"description": "LOCAO HID GRANA", "stock" : 210, "price" : 8.75},
{"description": "ESMALTE IMPALA ", "stock" : 224, "price" : 12.19},
{"description": "ESMALTE IMPALA ", "stock" : 345, "price" : 12.19},
{"description": "ESMALTE IMPALA ", "stock" : 420, "price" : 13.12},
{"description": "ESMALTE IMPALA ", "stock" : 235, "price" : 12.19},
{"description": "ESMALTE IMPALA ", "stock" : 199, "price" : 12.26},
{"description": "ESMALTE IMPALA ", "stock" : 160, "price" : 12.19},
{"description": "ESMALTE IMPALA ", "stock" : 148, "price" : 12.19},
{"description": "ESMALTE IMPALA ", "stock" : 161, "price" : 13.12},
{"description": "CR CONTRA ASSAD", "stock" : 148, "price" : 11.44},
{"description": "CR PENT SEDA 70", "stock" : 9, "price" : 12.15},
{"description": "DESCOLORANTE PO", "stock" : 1356, "price" : -0.05},
{"description": "DESCOLORANTE PO", "stock" : 2688, "price" : 0.81},
{"description": "DESCOLORANTE PO", "stock" : 540, "price" : 2.40},
{"description": "FRALDA DESC MIL", "stock" : 5, "price" : 27.02},
{"description": "FRALDA DESC MIL", "stock" : 3, "price" : 13.01},
{"description": "FRALDA DESC MIL", "stock" : 1260, "price" : 12.90},
{"description": "FRALDA DESC MIL", "stock" : 1, "price" : 14.09},
{"description": "FRALDA DESC GAL", "stock" : 1, "price" : 39.40},
{"description": "FRALDA DESC GAL", "stock" : 2668, "price" : 39.30},
{"description": "CR DT COLG GEL ", "stock" : 396, "price" : 4.04},
{"description": "SAB 4 ESTACOES ", "stock" : 86, "price" : 11.14},
{"description": "SAB 4 ESTACOES ", "stock" : 87, "price" : 11.14},
{"description": "SAB 4 ESTACOES ", "stock" : 112, "price" : 11.16},
{"description": "SAB 4 ESTACOES ", "stock" : 88, "price" : 11.13},
{"description": "DESOD AERO ABOV", "stock" : 624, "price" : 3.16},
{"description": "CR DT CLOSE-UP ", "stock" : 506, "price" : 18.70},
{"description": "ESMALTE IMPALA ", "stock" : 182, "price" : 11.05},
{"description": "ESMALTE IMPALA ", "stock" : 12, "price" : 10.35},
{"description": "ESMALTE IMPALA ", "stock" : 164, "price" : 11.05},
{"description": "ESMALTE IMPALA ", "stock" : 144, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 120, "price" : 10.26},
{"description": "KIT SH + COND P", "stock" : 273, "price" : 8.77},
{"description": "ESMALTE IMPALA ", "stock" : 157, "price" : 11.05},
{"description": "ESMALTE IMPALA ", "stock" : 182, "price" : 11.05},
{"description": "ESMALTE IMPALA ", "stock" : 136, "price" : 11.05},
{"description": "DESOD AERO ABOV", "stock" : 2196, "price" : 2.79},
{"description": "LENCO UMED GRAN", "stock" : 47, "price" : 5.90},
{"description": "POMADA HAIR BEI", "stock" : 1, "price" : 1.13},
{"description": "AMOLECEDOR DE C", "stock" : 48, "price" : 2.49},
{"description": "AMOLECEDOR DE C", "stock" : 36, "price" : 4.26},
{"description": "ABS INTIMUS GEL", "stock" : 645, "price" : 3.74},
{"description": "ABS INTIMUS GEL", "stock" : 688, "price" : 7.23},
{"description": "ABS INTIMUS GEL", "stock" : 304, "price" : 7.23},
{"description": "ABS INTIMUS DIA", "stock" : 470, "price" : 3.74},
{"description": "DESOD AERO ABOV", "stock" : 48, "price" : 3.18},
{"description": "DESOD AERO ABOV", "stock" : 912, "price" : 4.03},
{"description": "DESOD AERO ABOV", "stock" : 2, "price" : 3.01},
{"description": "DESOD AERO ABOV", "stock" : 612, "price" : 4.05},
{"description": "REPELENTE AERO ", "stock" : 1638, "price" : 4.31},
{"description": "DESOD AERO ABOV", "stock" : 3360, "price" : 2.69},
{"description": "DESOD AERO ABOV", "stock" : 2477, "price" : 2.69},
{"description": "DESOD AERO ABOV", "stock" : 24, "price" : 2.63},
{"description": "ALICATE CUT MUN", "stock" : 78, "price" : 3.30},
{"description": "SH PALM KIDS 35", "stock" : 180, "price" : 7.05},
{"description": "COND PALM KIDS ", "stock" : 54, "price" : 7.79},
{"description": "CR DT COLG SENS", "stock" : 288, "price" : 5.43},
{"description": "REPELENTE EXPOS", "stock" : 83, "price" : 24.88},
{"description": "FRALDA DESC HUG", "stock" : 12, "price" : 12.36},
{"description": "DESOD AERO BOZZ", "stock" : 429, "price" : 3.69},
{"description": "DESOD AERO BOZZ", "stock" : 201, "price" : 4.08},
{"description": "DESOD AERO BOZZ", "stock" : 240, "price" : 3.68},
{"description": "DESOD AERO BOZZ", "stock" : 294, "price" : 3.68},
{"description": "TINT KOLESTON 2", "stock" : 2, "price" : 10.97},
{"description": "TINT KOLESTON 2", "stock" : 162, "price" : 11.22},
{"description": "TINT KOLESTON 2", "stock" : 3, "price" : 12.64},
{"description": "TINT KOLESTON 2", "stock" : 24, "price" : 11.22},
{"description": "TINT KOLESTON 2", "stock" : 9, "price" : 12.64},
{"description": "TINT KOLESTON 2", "stock" : 33, "price" : 12.64},
{"description": "DESOD AERO REXO", "stock" : 576, "price" : 7.62},
{"description": "DESOD AERO REXO", "stock" : 876, "price" : 7.63},
{"description": "DESOD AERO REXO", "stock" : 396, "price" : 7.63},
{"description": "SAB LIQ DOVE 20", "stock" : 15, "price" : 3.47},
{"description": "SAB LIQ DOVE 20", "stock" : 219, "price" : 3.46},
{"description": "DESOD AERO AXE ", "stock" : 204, "price" : 5.93},
{"description": "DESOD AERO AXE ", "stock" : 228, "price" : 4.18},
{"description": "ALICATE CUT MUN", "stock" : 2, "price" : 3.33},
{"description": "ALICATE CUT MUN", "stock" : 4, "price" : 3.32},
{"description": "ALICATE CUT MUN", "stock" : 322, "price" : 3.33},
{"description": "SH MONANGE 325M", "stock" : 1, "price" : 3.15},
{"description": "COND MONANGE 32", "stock" : 18, "price" : 4.01},
{"description": "COND MONANGE 32", "stock" : 2, "price" : 3.90},
{"description": "COND MONANGE 32", "stock" : 180, "price" : 4.01},
{"description": "COND MONANGE 32", "stock" : 12, "price" : 3.89},
{"description": "COND MONANGE 32", "stock" : 6, "price" : 4.01},
{"description": "CR PENT MONANGE", "stock" : 549, "price" : 3.94},
{"description": "CR PENT MONANGE", "stock" : 750, "price" : 3.94},
{"description": "CR PENT MONANGE", "stock" : 51, "price" : 3.84},
{"description": "CR PENT MONANGE", "stock" : 777, "price" : 3.94},
{"description": "SH DOVE BABY 20", "stock" : 9, "price" : 5.28},
{"description": "MASCARA CONCENT", "stock" : 17, "price" : 12.25},
{"description": "MASCARA CONCENT", "stock" : 2, "price" : 12.25},
{"description": "DESOD AERO NIVE", "stock" : 540, "price" : 5.65},
{"description": "DESOD AERO NIVE", "stock" : 36, "price" : 5.84},
{"description": "DESOD AERO NIVE", "stock" : 564, "price" : 5.65},
{"description": "DESOD AERO NIVE", "stock" : 1020, "price" : 5.65},
{"description": "DESOD AERO NIVE", "stock" : 360, "price" : 5.65},
{"description": "DESOD AERO NIVE", "stock" : 276, "price" : 5.65},
{"description": "SAB ALBANY SUAV", "stock" : 1433, "price" : 8.45},
{"description": "KIT SH + COND D", "stock" : 2679, "price" : 21.17},
{"description": "PRESERVATIVO PR", "stock" : 852, "price" : 1.74},
{"description": "CR TRAT NIELY G", "stock" : 178, "price" : 10.07},
{"description": "CR PENT NIELY G", "stock" : 336, "price" : 2.99},
{"description": "CR PENT NIELY G", "stock" : 708, "price" : 3.58},
{"description": "CR PENT NIELY G", "stock" : 1587, "price" : 3.59},
{"description": "CR PENT NIELY G", "stock" : 105, "price" : 6.48},
{"description": "SAB LIQ LUX BOT", "stock" : 246, "price" : 2.67},
{"description": "SAB LIQ LUX BOT", "stock" : 1, "price" : 1.50},
{"description": "DESOD ROLL-ON N", "stock" : 581, "price" : 3.27},
{"description": "DESOD ROLL-ON N", "stock" : 640, "price" : 3.27},
{"description": "DESOD ROLL-ON N", "stock" : 1164, "price" : 3.27},
{"description": "DESOD ROLL-ON N", "stock" : 19, "price" : 3.27},
{"description": "DESOD ROLL-ON N", "stock" : 1, "price" : 3.27},
{"description": "DESOD ROLL-ON N", "stock" : 83, "price" : 3.27},
{"description": "CR HIDR NIVEA 5", "stock" : 2, "price" : 6.97},
{"description": "CR HIDR NIVEA 4", "stock" : 78, "price" : 6.97},
{"description": "CR HIDR NIVEA 9", "stock" : 12, "price" : 9.87},
{"description": "CR BARB NIVEA 6", "stock" : 3, "price" : 2.15},
{"description": "CR BARB NIVEA 6", "stock" : 4, "price" : 2.15},
{"description": "CERA MODELADORA", "stock" : 275, "price" : 9.15},
{"description": "ESPUMA BARB BOZ", "stock" : 15, "price" : 10.84},
{"description": "ESPUMA BARB BOZ", "stock" : 9, "price" : 11.03},
{"description": "ESPUMA BARB BOZ", "stock" : 6, "price" : 10.84},
{"description": "CR BARB BOZZANO", "stock" : 432, "price" : 3.17},
{"description": "CR BARB BOZZANO", "stock" : 36, "price" : 3.19},
{"description": "CR BARB BOZZANO", "stock" : 60, "price" : 3.19},
{"description": "GEL FIXADOR BOZ", "stock" : 228, "price" : 5.49},
{"description": "DESOD ROLL-ON N", "stock" : 67, "price" : 3.27},
{"description": "DESOD ROLL-ON N", "stock" : 3, "price" : 3.27},
{"description": "DESOD ROLL-ON N", "stock" : 120, "price" : 3.27},
{"description": "DESOD ROLL-ON N", "stock" : 1, "price" : 3.27},
{"description": "SAB LIQ DOVE 20", "stock" : 18, "price" : 3.47},
{"description": "ESMALTE IMPALA ", "stock" : 158, "price" : 11.05},
{"description": "SAB LIQ HIDRAMA", "stock" : 6, "price" : 7.62},
{"description": "GEL HIG P/MAOS ", "stock" : 267, "price" : 3.30},
{"description": "FRALDA DESC HUG", "stock" : 439, "price" : 19.31},
{"description": "ESMALTE IMPALA ", "stock" : 124, "price" : 11.05},
{"description": "ESMALTE IMPALA ", "stock" : 1801, "price" : 10.24},
{"description": "ESMALTE IMPALA ", "stock" : 239, "price" : 10.27},
{"description": "SAB NIVEA 6X90G", "stock" : 409, "price" : 6.29},
{"description": "SAB NIVEA 6X85G", "stock" : 533, "price" : 3.29},
{"description": "SAB NIVEA 6X85G", "stock" : 1, "price" : 3.29},
{"description": "FRALDA DESC HUG", "stock" : 33, "price" : 7.56},
{"description": "FRALDA DESC HUG", "stock" : 1032, "price" : 5.93},
{"description": "FRALDA DESC HUG", "stock" : 12, "price" : 7.56},
{"description": "SAB NIVEA 3X90G", "stock" : 740, "price" : 2.65},
{"description": "SAB NIVEA 2X90G", "stock" : 1041, "price" : 1.43},
{"description": "DESOD AERO NIVE", "stock" : 2, "price" : 9.26},
{"description": "FRALDA DESC HUG", "stock" : 7, "price" : 13.05},
{"description": "SAB LIQ REXONA ", "stock" : 39, "price" : 4.39},
{"description": "SAB LIQ REXONA ", "stock" : 102, "price" : 4.39},
{"description": "CR DT COLG TOTA", "stock" : 488, "price" : 86.25},
{"description": "CR DT SORRISO E", "stock" : 380, "price" : 22.64},
{"description": "SAB PALM NATURA", "stock" : 790, "price" : 10.72},
{"description": "SAB PALM NATURA", "stock" : 376, "price" : 18.82},
{"description": "CR DT COLG TOTA", "stock" : 1, "price" : 92.43},
{"description": "SH CLEAR ANTIC ", "stock" : 1077, "price" : 10.47},
{"description": "ALCOOL GEL REXO", "stock" : 317, "price" : 3.26},
{"description": "SAB FRANCIS ARO", "stock" : 1070, "price" : 9.13},
{"description": "ESPONJA P/BANHO", "stock" : 420, "price" : 0.34},
{"description": "SH KOLENE 300ML", "stock" : 840, "price" : 3.19},
{"description": "COND KOLENE 300", "stock" : 921, "price" : 3.64},
{"description": "CR TRAT KOLENE ", "stock" : 795, "price" : 7.11},
{"description": "SH KOLENE 300ML", "stock" : 555, "price" : 3.17},
{"description": "COND KOLENE 300", "stock" : 762, "price" : 3.57},
{"description": "HAIR SPRAY KARI", "stock" : 333, "price" : 8.59},
{"description": "HAIR SPRAY KARI", "stock" : 408, "price" : 6.99},
{"description": "HAIR SPRAY KARI", "stock" : 417, "price" : 6.99},
{"description": "HAIR SPRAY KARI", "stock" : 321, "price" : 8.59},
{"description": "HAIR SPRAY KARI", "stock" : 159, "price" : 8.59},
{"description": "GEL FIXADOR KAR", "stock" : 15, "price" : 5.69},
{"description": "CR TRAT KOLENE ", "stock" : 233, "price" : 7.19},
{"description": "CR TRAT NEUTROX", "stock" : 1035, "price" : 9.27},
{"description": "CR TRAT NEUTROX", "stock" : 1010, "price" : 9.27},
{"description": "CR TRAT NEUTROX", "stock" : 1031, "price" : 9.27},
{"description": "SAB FRANCIS ARO", "stock" : 1362, "price" : 9.13},
{"description": "PROTETOR LABIAL", "stock" : 17, "price" : 5.46},
{"description": "PROTETOR LABIAL", "stock" : 120, "price" : 5.46},
{"description": "PROTETOR LABIAL", "stock" : 5, "price" : 5.46},
{"description": "PROTETOR LABIAL", "stock" : 108, "price" : 5.46},
{"description": "PROTETOR LABIAL", "stock" : 84, "price" : 5.46},
{"description": "ESMALTE IMPALA ", "stock" : 290, "price" : 12.25},
{"description": "ESMALTE IMPALA ", "stock" : 154, "price" : 12.26},
{"description": "ESMALTE IMPALA ", "stock" : 110, "price" : 12.19},
{"description": "ESMALTE IMPALA ", "stock" : 250, "price" : 13.12},
{"description": "ESMALTE IMPALA ", "stock" : 150, "price" : 12.19},
{"description": "ESMALTE IMPALA ", "stock" : 146, "price" : 13.12},
{"description": "ESMALTE IMPALA ", "stock" : 149, "price" : 12.19},
{"description": "ESMALTE IMPALA ", "stock" : 155, "price" : 13.12},
{"description": "PROTETOR SOLAR ", "stock" : 1, "price" : 23.40},
{"description": "ABS INTIMUS ANT", "stock" : 342, "price" : 1.93},
{"description": "ABS INTIMUS ANT", "stock" : 40, "price" : 4.63},
{"description": "SAB LIQ INTIMUS", "stock" : 162, "price" : 8.57},
{"description": "CR DT COLG TOTA", "stock" : 99, "price" : 22.88},
{"description": "ESC DT SORRISO ", "stock" : 69, "price" : 16.65},
{"description": "ESC DT COLG COL", "stock" : 18, "price" : 17.33},
{"description": "SH NEUTROX 300M", "stock" : 735, "price" : 3.47},
{"description": "COND NEUTROX 30", "stock" : 759, "price" : 3.69},
{"description": "CR TRAT NEUTROX", "stock" : 592, "price" : 8.80},
{"description": "LOCAO HID VASEN", "stock" : 48, "price" : 7.96},
{"description": "LOCAO HID VASEN", "stock" : 102, "price" : 16.10},
{"description": "LOCAO HID VASEN", "stock" : 12, "price" : 7.96},
{"description": "LOCAO HID VASEN", "stock" : 105, "price" : 14.44},
{"description": "LOCAO HID VASEN", "stock" : 87, "price" : 11.05},
{"description": "LOCAO HID VASEN", "stock" : 36, "price" : 20.01},
{"description": "LOCAO HID VASEN", "stock" : 114, "price" : 11.74},
{"description": "LOCAO HID VASEN", "stock" : 102, "price" : 11.05},
{"description": "LOCAO HID VASEN", "stock" : 87, "price" : 10.12},
{"description": "SAB LIQ HUGGIES", "stock" : 3, "price" : 5.92},
{"description": "SAB LIQ HUGGIES", "stock" : 159, "price" : 14.58},
{"description": "SAB LIQ HUGGIES", "stock" : 147, "price" : 4.19},
{"description": "SH HUGGIES 200M", "stock" : 1, "price" : 4.00},
{"description": "SH HUGGIES 600M", "stock" : 51, "price" : 10.25},
{"description": "ABS PLENITUDE F", "stock" : 336, "price" : 2.86},
{"description": "ABS PLENITUDE F", "stock" : 260, "price" : 3.47},
{"description": "HASTES FLEX COT", "stock" : 552, "price" : 1.41},
{"description": "PINCA MUNDIAL F", "stock" : 282, "price" : 2.57},
{"description": "REPELENTE NO IN", "stock" : 1038, "price" : 5.39},
{"description": "REPELENTE NO IN", "stock" : 1083, "price" : 5.39},
{"description": "REPELENTE NO IN", "stock" : 1020, "price" : 5.39},
{"description": "REPELENTE NO IN", "stock" : 231, "price" : 5.96},
{"description": "REPELENTE AERO ", "stock" : 853, "price" : 5.97},
{"description": "DESOD AERO ABOV", "stock" : 2088, "price" : 2.70},
{"description": "DESOD AERO ABOV", "stock" : 2518, "price" : 2.70},
{"description": "DESOD AERO ABOV", "stock" : 2448, "price" : 2.70},
{"description": "DESOD AERO ABOV", "stock" : 2616, "price" : 2.70},
{"description": "LENCO UMED HUGG", "stock" : 385, "price" : 3.86},
{"description": "FRALDA DESC HUG", "stock" : 2, "price" : 13.05},
{"description": "FRALDA DESC HUG", "stock" : 189, "price" : 19.53},
{"description": "FRALDA DESC HUG", "stock" : 99, "price" : 19.53},
{"description": "FRALDA DESC HUG", "stock" : 42, "price" : 19.53},
{"description": "FRALDA DESC HUG", "stock" : 348, "price" : 19.53},
{"description": "COND PALM NATUR", "stock" : 354, "price" : 5.15},
{"description": "PRESERVATIVO DU", "stock" : 984, "price" : 2.00},
{"description": "PRESERVATIVO DU", "stock" : 168, "price" : 2.00},
{"description": "PRESERVATIVO DU", "stock" : 792, "price" : 2.50},
{"description": "PRESERVATIVO DU", "stock" : 1584, "price" : 2.50},
{"description": "PRESERVATIVO DU", "stock" : 72, "price" : 1.50},
{"description": "AP BARB PERSONN", "stock" : 764, "price" : 10.15},
{"description": "AP BARB PERSONN", "stock" : 334, "price" : 26.34},
{"description": "AP BARB PERSONN", "stock" : 520, "price" : 7.55},
{"description": "AP BARB PERSONN", "stock" : 1019, "price" : 8.22},
{"description": "AP BARB PERSONN", "stock" : 224, "price" : 19.08},
{"description": "AP BARB PERSONN", "stock" : 743, "price" : 33.60},
{"description": "AP BARB PERSONN", "stock" : 362, "price" : 19.43},
{"description": "SH SEDA 325ML O", "stock" : 6, "price" : 4.30},
{"description": "COND SEDA 325ML", "stock" : 858, "price" : 5.58},
{"description": "CR PENT SEDA 30", "stock" : 666, "price" : 4.34},
{"description": "COND SEDA 325ML", "stock" : 2727, "price" : 5.58},
{"description": "SH SEDA 325ML C", "stock" : 2907, "price" : 4.29},
{"description": "SH SEDA 325ML P", "stock" : 834, "price" : 4.12},
{"description": "COND SEDA 170ML", "stock" : 576, "price" : 6.44},
{"description": "SH DOVE 400ML H", "stock" : 276, "price" : 8.82},
{"description": "COND DOVE 400ML", "stock" : 195, "price" : 10.51},
{"description": "COND TRESEMME 4", "stock" : 222, "price" : 8.41},
{"description": "COND TRESEMME 1", "stock" : 576, "price" : 10.05},
{"description": "CR PENT TRESEMM", "stock" : 579, "price" : 5.14},
{"description": "COND SEDA 325ML", "stock" : 1476, "price" : 5.57},
{"description": "SH SEDA 325ML B", "stock" : 988, "price" : 4.30},
{"description": "FRALDA DESC HUG", "stock" : 998, "price" : 37.49},
{"description": "SH NIELY GOLD 2", "stock" : 330, "price" : 4.10},
{"description": "COND NIELY GOLD", "stock" : 300, "price" : 3.98},
{"description": "COND NIELY GOLD", "stock" : 375, "price" : 3.98},
{"description": "SH NIELY GOLD 2", "stock" : 267, "price" : 4.10},
{"description": "SH NIELY GOLD 2", "stock" : 549, "price" : 4.10},
{"description": "CR DT CLOSE-UP ", "stock" : 2247, "price" : 6.94},
{"description": "CR DT CLOSE-UP ", "stock" : 3212, "price" : 6.95},
{"description": "SH NIELY GOLD 2", "stock" : 3, "price" : 4.10},
{"description": "LOCAO HID GRANA", "stock" : 60, "price" : 8.75},
{"description": "CR DT SORRISO T", "stock" : 211, "price" : 25.70},
{"description": "ESC DT COLG SMI", "stock" : 15, "price" : 6.84},
{"description": "SH NIELY GOLD 2", "stock" : 519, "price" : 3.14},
{"description": "ESC DT COLG KID", "stock" : 114, "price" : 11.07},
{"description": "ESC DT COLG SLI", "stock" : 27, "price" : 27.34},
{"description": "ANT-SEPT BUC CO", "stock" : 63, "price" : 10.19},
{"description": "ANT-SEPT BUC CO", "stock" : 42, "price" : 12.86},
{"description": "SAB PROTEX 12X8", "stock" : 819, "price" : 18.01},
{"description": "DESOD AERO DOVE", "stock" : 472, "price" : 123.29},
{"description": "SPRAY HIG P/MAO", "stock" : 9, "price" : 9.46},
{"description": "ABS INTIMUS INT", "stock" : 729, "price" : 5.24},
{"description": "ABS INTIMUS INT", "stock" : 662, "price" : 5.24},
{"description": "ABS INTIMUS INT", "stock" : 603, "price" : 5.24},
{"description": "ABS INTIMUS INT", "stock" : 654, "price" : 8.14},
{"description": "LENCO UMED HUGG", "stock" : 518, "price" : 5.05},
{"description": "COND NIELY GOLD", "stock" : 1239, "price" : 3.98},
{"description": "COND NIELY GOLD", "stock" : 681, "price" : 3.98},
{"description": "ESMALTE IMPALA ", "stock" : 287, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 277, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 288, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 283, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 307, "price" : 10.30},
{"description": "ESMALTE IMPALA ", "stock" : 289, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 290, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 292, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 288, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 293, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 309, "price" : 10.30},
{"description": "ESMALTE IMPALA ", "stock" : 293, "price" : 10.26},
{"description": "ESMALTE IMPALA ", "stock" : 310, "price" : 10.30},
{"description": "PRESERVATIVO DU", "stock" : 108, "price" : 2.23},
{"description": "PRESERVATIVO DU", "stock" : 324, "price" : 2.23},
{"description": "SAB PROTEX BABY", "stock" : 110, "price" : 19.29},
{"description": "SAB LIQ PROTEX ", "stock" : 180, "price" : 4.26},
{"description": "SAB LIQ PROTEX ", "stock" : 108, "price" : 9.50},
{"description": "SAB LIQ PROTEX ", "stock" : 132, "price" : 8.48},
{"description": "LENCO UMED PROT", "stock" : 25, "price" : 7.10},
{"description": "CR DT COLG LUMI", "stock" : 84, "price" : 90.14},
{"description": "DESOD AERO ABOV", "stock" : 4380, "price" : 4.46},
{"description": "DESOD AERO ABOV", "stock" : 2784, "price" : 4.47},
{"description": "DESOD AERO ABOV", "stock" : 2538, "price" : 4.42},
{"description": "DESOD AERO ABOV", "stock" : 2616, "price" : 4.42},
{"description": "DESOD AERO ABOV", "stock" : 2088, "price" : 4.47},
{"description": "DESOD AERO ABOV", "stock" : 2694, "price" : 4.42},
{"description": "DESOD AERO ABOV", "stock" : 12, "price" : 1.51},
{"description": "DESOD AERO ABOV", "stock" : 120, "price" : 1.51},
{"description": "DESOD AERO ABOV", "stock" : 120, "price" : 1.51},
{"description": "DESOD AERO ABOV", "stock" : 1836, "price" : 1.51},
{"description": "DESOD AERO ABOV", "stock" : 504, "price" : 1.51},
{"description": "DESOD AERO ABOV", "stock" : 120, "price" : 1.51},
{"description": "DESOD AERO ABOV", "stock" : 120, "price" : 1.51},
{"description": "DESOD AERO ABOV", "stock" : 120, "price" : 1.51},
{"description": "DESOD AERO ABOV", "stock" : 204, "price" : 1.51},
{"description": "DESOD AERO ABOV", "stock" : 156, "price" : 1.51},
{"description": "DESOD AERO ABOV", "stock" : 252, "price" : 1.51},
{"description": "DESOD AERO ABOV", "stock" : 120, "price" : 1.51},
{"description": "DESOD AERO ABOV", "stock" : 216, "price" : 1.51},
{"description": "DESOD AERO ABOV", "stock" : 120, "price" : 1.51},
{"description": "DESOD AERO ABOV", "stock" : 120, "price" : 1.51},
{"description": "DESOD AERO ABOV", "stock" : 144, "price" : 1.51},
{"description": "DESOD AERO ABOV", "stock" : 120, "price" : 1.51},
{"description": "ABS MILI SUAVE ", "stock" : 480, "price" : 0.48},
{"description": "CR DT SORRISO T", "stock" : 374, "price" : 38.60},
{"description": "LOCAO HID DOVE ", "stock" : 357, "price" : 5.33},
{"description": "LOCAO HID DOVE ", "stock" : 375, "price" : 5.33},
{"description": "REPELENTE OFF F", "stock" : 288, "price" : 10.66},
{"description": "SH CLEAR ANTIC ", "stock" : 822, "price" : 10.46},
{"description": "COND DOVE 400ML", "stock" : 171, "price" : 7.67},
{"description": "COND DOVE 400ML", "stock" : 651, "price" : 7.67},
{"description": "KIT SH + COND N", "stock" : 1313, "price" : 7.44},
{"description": "KIT SH + COND N", "stock" : 1146, "price" : 7.44},
{"description": "KIT SH + COND N", "stock" : 603, "price" : 7.43},
{"description": "KIT SH + COND N", "stock" : 925, "price" : 7.44}];

WidgetsFlutterBinding.ensureInitialized();
await Firebase.initializeApp();

CollectionReference productdb = FirebaseFirestore.instance.collection('product');

var mumber = 1;
for (int b=0;b<productsList.length;b++)
{
//Product product = productslist[b] as Product;
mumber = mumber + 1;
productdb.doc(mumber.toString()).set(productsList[b]);


// products.doc(mumber.toString()).set(product.toJson());
    {

}
}

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

class Detail extends StatelessWidget {
  final Product product;

  const Detail({this.product});

  @override
  Widget build(BuildContext context) {
    return Card(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Text( product.description,
              style: Theme.of(context).textTheme.headline1),
          Container(
            margin: EdgeInsets.only(left: 2, right: 16, bottom: 16, top: 8),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: <Widget>[
                Text('Preço: ' + product.price.toString(),
                    style: Theme.of(context).textTheme.headline2),
                Text(
                  'Estoque: ' + product.price.toString(),
                  style: Theme.of(context).textTheme.headline2,
                ),
                FlatButton(
                  color: Theme.of(context).primaryColor,
                  onPressed: () {},
                  child:
                      Text('Adicionar', style: TextStyle(color: Colors.white)),
                )
              ],
            ),
          )
        ],
      ),
    );
  }
}

